--WHERE절
SELECT * FROM EMP WHERE DEPTNO = 30;

--AND 연산자
SELECT * FROM EMP WHERE DEPTNO = 30 AND JOB = 'SALESMAN';

--OR 연산자
SELECT * FROM EMP WHERE DEPTNO = 30 OR JOB = 'CLERK';

--산술 연산자
SELECT * FROM EMP WHERE SAL * 12 = 36000;

--비교 연산자
SELECT * FROM EMP WHERE SAL >= 3000;

--비교 연산자 (문자열)
SELECT * FROM EMP WHERE ENAME >= 'F';

--비교 연산자 (문자열 여러개)
SELECT * FROM EMP WHERE ENAME <= 'FORZ';

--등가 비교 연산자
SELECT * FROM EMP WHERE SAL != 3000;
SELECT * FROM EMP WHERE SAL <> 3000;
SELECT * FROM EMP WHERE SAL^= 3000;

--논리 부정 연산자
SELECT * FROM EMP WHERE NOT SAL= 3000;