-- 집합 연산자
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
    UNION
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 20;

--집합 연산자(출력할 열 개수가 다를 때)
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
    UNION
SELECT EMPNO, ENAME, SAL FROM EMP WHERE DEPTNO = 20;

--집합 연산자(출력할 열의 자료형이 다를 때)
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
    UNION
SELECT ENAME, EMPNO, DEPTNO, SAL FROM EMP WHERE DEPTNO = 20;

/* 집합 연산자는 출력할 열의 개수와 자료형이 같으면 
열 이름이 달라도 문제가 되지 않는다.*/
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
    UNION
SELECT SAL, JOB, DEPTNO, SAL FROM EMP WHERE DEPTNO = 20;

--UNION과 UNION ALL의 차이
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
    UNION
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;

-- UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
    UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;

-- MINUS 사용
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
    MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
    WHERE DEPTNO = 10;
    
-- INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
    INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
    WHERE DEPTNO = 10;