CREATE TABLE MEMBER(
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(128) NOT NULL,
  EMAIL VARCHAR2(256) NOT NULL UNIQUE,
  AGE NUMBER
);

CREATE SEQUENCE mem_seq
  INCREMENT BY 1
  START WITH 1
  NOCYCLE
  NOCACHE
  NOORDER
;
INSERT INTO MEMBER (ID, NAME, EMAIL, AGE)
VALUES (MEM_SEQ.NEXTVAL, '윤서준', 'SeojunYoon@hanbit.co.kr', 10);
INSERT INTO MEMBER (ID, NAME, EMAIL, AGE)
VALUES (MEM_SEQ.NEXTVAL, '윤광철', 'Kwangcheol@hanbit.co.kr', 43);
INSERT INTO MEMBER (ID, NAME, EMAIL, AGE)
VALUES (MEM_SEQ.NEXTVAL, '공미영', 'MiyeongKong@hanbit.co.kr', 23);
INSERT INTO MEMBER (ID, NAME, EMAIL, AGE)
VALUES (MEM_SEQ.NEXTVAL, '김도윤', 'DoyoonKim@hanbit.co.kr', 10);
ALTER TABLE MEMBER MODIFY (ID NUMBER DEFAULT mem_seq.NEXTVAL NOT NULL);

SELECT * FROM MEMBER;

COMMIT;

