CREATE TABLE ARTICLE(
  ID NUMBER,
  TITLE VARCHAR2(256),
  DESCRIPTION VARCHAR2(1000),
  CREATED DATE,
  UPDATED DATE,
  MEMBER_ID NUMBER,
  FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(ID) ON DELETE CASCADE
);

CREATE SEQUENCE article_seq
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOCYCLE
  NOORDER;
ALTER TABLE ARTICLE MODIFY (ID NUMBER DEFAULT article_seq.NEXTVAL NOT NULL);

SELECT * FROM ARTICLE;
COMMIT;

INSERT INTO ARTICLE(ID, TITLE, DESCRIPTION, CREATED, UPDATED, MEMBER_ID) VALUES (article_seq.NEXTVAL, '첫 번째 제목', '첫 번째 본문', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO ARTICLE(ID, TITLE, DESCRIPTION, CREATED, UPDATED, MEMBER_ID) VALUES (article_seq.NEXTVAL, '두 번째 제목', '두 번째 본문', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2);
INSERT INTO ARTICLE(ID, TITLE, DESCRIPTION, CREATED, UPDATED, MEMBER_ID) VALUES (article_seq.NEXTVAL, '세 번째 제목', '세 번째 본문', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3);
INSERT INTO ARTICLE(ID, TITLE, DESCRIPTION, CREATED, UPDATED, MEMBER_ID) VALUES (article_seq.NEXTVAL, '네 번째 제목', '네 번째 본문', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4);
COMMIT;

drop table article;
drop table member;
drop sequence mem_seq;
drop sequence article_seq;