-- 1
SELECT * FROM EMP WHERE ENAME LIKE '%S';

-- 2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 30 AND JOB = 'SALESMAN';

-- 3(집합연산자 사용 X)
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE DEPTNO IN(20, 30)
    AND (SAL > 2000);
    
-- 3(집합연산자 사용 O)
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
    WHERE DEPTNO IN(20, 30)
    INTERSECT
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP    
    WHERE SAL > 2000;
    
-- 4
SELECT * FROM EMP WHERE SAL < 2000 OR SAL > 3000;
SELECT * FROM EMP WHERE NOT (SAL>= 2000 AND SAL <= 3000);

-- 5
SELECT ENAME, EMPNO, SAL, DEPTNO FROM EMP 
WHERE SAL NOT BETWEEN 1000 AND 2000 
    AND DEPTNO = 30 
    AND ENAME LIKE '%E%';
    
-- 5-1
SELECT ENAME, EMPNO, SAL, DEPTNO FROM EMP 
WHERE SAL NOT BETWEEN 1000 AND 2000 AND DEPTNO = 30
    INTERSECT
SELECT ENAME, EMPNO, SAL, DEPTNO FROM EMP 
WHERE ENAME LIKE '%E%';

-- 6 
SELECT * FROM EMP WHERE COMM IS NULL
    AND MGR IS NOT NULL
    AND JOB IN('MANAGER', 'CLERK')
    AND ENAME NOT LIKE '_L%';
    
