CREATE TABLE TBL_STUDENT(
  SNO VARCHAR2(8 CHAR) PRIMARY KEY,
  SNAME VARCHAR2(10 CHAR) NOT NULL,
  SYEAR NUMBER(1) NOT NULL,
  GENDER VARCHAR2(3 CHAR) NOT NULL,
  MAJOR VARCHAR2(20 CHAR) NOT NULL,
  SCORE NUMBER(3)
);

INSERT INTO TBL_STUDENT (SNO, SNAME, SYEAR, GENDER, MAJOR, SCORE) 
  VALUES ('25121101', '홍길동', 1, '남', '체육학과', 75);

INSERT INTO TBL_STUDENT (SNO, SNAME, SYEAR, GENDER, MAJOR, SCORE) 
  VALUES ('25121102', '이몽룡', 1, '남', '의대학과', 98);
  
INSERT INTO TBL_STUDENT (SNO, SNAME, SYEAR, GENDER, MAJOR, SCORE) 
  VALUES ('25121103', '성춘향', 2, '여', '경영학과', 88);

INSERT INTO TBL_STUDENT (SNO, SNAME, SYEAR, GENDER, MAJOR, SCORE) 
  VALUES ('25121104', '정자바', 3, '남', '컴퓨터학과', 92);  


DESC EMP;