--1
--EMP 테이블 정의
CREATE TABLE EMP(
  EMPNO NUMBER(4) PRIMARY KEY,
  ENAME VARCHAR2(20),
  JOB VARCHAR2(10),
  MGR NUMBER(4),
  HIREDATE DATE,
  SAL NUMBER(4),
  COMM NUMBER(4),
  DEPTNO NUMBER(2) REFERENCES DEPT(DEPTNO)
);
-- DEPT 테이블 정의
CREATE TABLE DEPT(
  DEPTNO NUMBER(2) PRIMARY KEY,
  DNAME VARCHAR2(20),
  LOC VARCHAR2(20)
);

--2)
DELETE FROM DEPT WHERE DEPTNO=40;

--3)
SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, INDEX_NAME FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP';

--4)
SELECT * FROM EMP ORDER BY SAL DESC;

--5)
SELECT * FROM EMP WHERE ENAME LIKE 'S%T' AND LENGTH(ENAME) = 5;

--6)
SELECT E.ENAME, D.DNAME, E.SAL, E.JOB FROM EMP E JOIN DEPT D USING (DEPTNO)
WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN');

--7)
SELECT EMPNO, ENAME, SAL FROM EMP E
WHERE SAL > (SELECT MAX(SAL) FROM EMP WHERE DEPTNO=30);

--8)
SELECT * FROM EMP WHERE COMM IS NOT NULL;

--9)
SELECT ENAME, JOB, SAL,
  CASE 
    WHEN SAL>=3000 THEN SAL+(SAL*0.15)
    WHEN SAL>=2000 THEN SAL+(SAL*0.1)
    WHEN SAL>=1000 THEN SAL+(SAL*0.05)
    ELSE SAL
  END AS INCENTIVE
  FROM EMP;
  
--10)
SELECT E.EMPNO, E.ENAME, D.DNAME, D.LOC, E.SAL 
  FROM EMP E JOIN DEPT D USING (DEPTNO)
  WHERE JOB IN (SELECT JOB FROM EMP WHERE DEPTNO=10)
  ORDER BY SAL DESC;