CREATE TABLE TABLE_CHECK(
    LOGIN_ID    VARCHAR(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD  VARCHAR(20) CONSTRAINT TBLCK_LOGINPW_CK CHECK(LENGTH(LOGIN_PWD) > 3),
    TEL         VARCHAR(20)
);

DESC TABLE_CHECK;

--CHCK제약조건에 맞지 않는 예
INSERT INTO TABLE_CHECK VALUES('TEST_ID', '123', '010-1234-5678');

--CHECK 제약조건에 맞는 예
INSERT INTO TABLE_CHECK VALUES('TEST_ID', '1234', '010-1234-5678');
SELECT * FROM TABLE_CHECK;

-- 데이터 사전 확인
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_CHECK';