CREATE TABLE TABLE_DEFAULT(
    LOGIN_ID    VARCHAR(20) CONSTRAINT TBLCK2_LGNID_PK PRIMARY KEY,
    LOGIN_PWD   VARCHAR(20) DEFAULT '1234',
    TEL         VARCHAR(20)
);
DESC TABLE_DEFAULT;

-- DEFAULT로 지정한 기본값 확인
INSERT INTO TABLE_DEFAULT VALUES('TEST_ID', NULL, '010-1234-5678');
INSERT INTO TABLE_DEFAULT (LOGIN_ID, TEL) VALUES ('TEST_ID2', '010-1234-5678');
SELECT * FROM TABLE_DEFAULT;