SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, R_OWNER, R_CONSTRAINT_NAME
    FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN('EMP', 'DEPT');

--EMP테이블에 DEPTNO열 50으로 지정한 값을 저장
INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(9999, '홍길동', 'CLERK', '7788', TO_DATE('2017/04/30', 'YYYY/MM/DD'), 1200, NULL, 50);

--dept테이블 확인
SELECT * FROM DEPT;

--FOREIGN KEY 지정 DEPT_FK, EMP_FK 테이블 생성
CREATE TABLE DEPT_FK(
    DEPTNO  NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
    DNAME   VARCHAR2(14),
    LOC     VARCHAR2(13)
);
DESC DEPT_FK;

-- EMP_FK 테이블 생성
CREATE TABLE EMP_FK(
    EMPNO   NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9),
    MGR     VARCHAR2(4),
    HIREDATE    DATE,
    SAL     NUMBER(7, 2),
    COMM    NUMBER(7, 2),
    DEPTNO  NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO)
);

DESC EMP_FK;

--DEPT_FK에 데이터 삽입
INSERT INTO DEPT_FK VALUES(10, 'TEST_DNAME', 'TEST_LOC');
SELECT * FROM DEPT_FK;

--EMP_FK에 데이터 삽입
INSERT INTO EMP_FK VALUES(9999, 'TEST_NAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01', 'YYYY/MM/DD'),
    3000, NULL, 10);
SELECT * FROM EMP_FK;    
    
-- FOREIGN KEY로 참조 행 데이터 삭제
DELETE FROM DEPT_FK WHERE DEPTNO = 10;