-- 테이블을 생성할 때 NOT NULL 설정
CREATE TABLE EMP_NOTNULL(
    LOGIN_ID    VARCHAR2(20) NOT NULL,
    LOGIN_PW    VARCHAR2(20) NOT NULL,
    TEL         VARCHAR2(20)
);
DESC EMP_NOTNULL;

ALTER TABLE EMP_NOTNULL RENAME COLUMN LOGIN_PW TO LOGIN_PWD;
-- 제약 조건이 없는 TEL에  NULL 입력
INSERT INTO EMP_NOTNULL(LOGIN_ID, LOGIN_PWD)
VALUES('test_id_01', '1234');
SELECT * FROM EMP_NOTNULL;

-- NOT NULL제약 조건이 지정된 열 데이터를 NULL로 업데이트 하기
UPDATE TABLE_NOTNULL SET LOGIN_PWD=NULL
WHERE LOGIN_ID = 'test_id_01';

-- soctt계정의 제약 조건 확인
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS;

--제약조건 이름 직접 지정
CREATE TABLE TABLE_NOTNULL2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLNN2_LGNID_NN NOT NULL,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLNN2_LGNPW_NN NOT NULL,
    TEL VARCHAR2(20)
);

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS; 

--이미 생성한 테이블에 제약 조건 지정
ALTER TABLE TABLE_NOTNULL MODIFY(TEL NOT NULL);

--기존 tel 열을 null이 아닌 데이터로 수정
UPDATE TABLE_NOTNULL SET TEL = '010-1234-5678' WHERE LOGIN_ID = 'test_id_01';
SELECT * FROM TABLE_NOTNULL;

--not null 제약 조건 추가하기
ALTER TABLE TABLE_NOTNULL MODIFY(TEL NOT NULL);
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS; 


-- 제약 조건에 이름을 지정해서 추가하기
ALTER TABLE TABLE_NOTNULL2 MODIFY(TEL CONSTRAINT TBLNN_TEL_NN NOT NULL);
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS; 

-- 이미 생성한 제약 조건 이름 변경하기
ALTER TABLE TABLE_NOTNULL2 RENAME CONSTRAINT TBLNN_TEL_NN TO TBLNN2_TEL_NN;
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS; 

-- 제약 조건 삭제
ALTER TABLE TABLE_NOTNULL2 DROP CONSTRAINT TBLNN2_TEL_NN;
DESC TABLE_NOTNULL2;