--테이블 생성하며 제약조건
CREATE TABLE TABLE_PK(
    LOGIN_ID    VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD   VARCHAR2(20) NOT NULL,
    TEL         VARCHAR2(20)
);
desc TABLE_PK;

-- 데이터 사전 확인
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_PK%';

-- USER_INDEXES 조회
SELECT INDEX_NAME, TABLE_OWNER, TABLE_NAME FROM USER_INDEXES
WHERE TABLE_NAME LIKE 'TABLE_PK%';

--TABLE_PK에 데이터 입력
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01', 'PWD01', '010-1234-5678');
SELECT * FROM TABLE_PK;

--중복데이터 입력
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01', 'PWD01', '010-1234-5678');

-- NULL입력
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES(NULL, 'PWD02', '010-0000-8888');

-- 테이블 생성하며 제약 조건 이름 지정
CREATE TABLE TABLE_PK2(
    LOGIN_ID    VARCHAR2(20) CONSTRAINT TBLPK2_LGNID_PK PRIMARY KEY,
    LOGIN_PWD   VARCHAR2(20) CONSTRAINT TBLPK2_LGNID_NN NOT NULL,
    TEL         VARCHAR2(20)
);
DESC TABLE_PK2;
