-- 테이블 전체 열 출력
SELECT * FROM EMP;

-- 테이블 부분 열 출력
SELECT EMPNO, ENAME, DEPTNO FROM EMP;

-- 중복데이터 가리기
SELECT DISTINCT DEPTNO FROM EMP;

-- 여러개의 열  중복 제거
SELECT DISTINCT JOB, DEPTNO FROM EMP;

-- ALL로 중복되는 열 제거하지 않고 그대로 출력
SELECT ALL JOB, DEPTNO FROM EMP;

SELECT JOB, DEPTNO FROM EMP;

-- 열에 연산식 사용(급여 * 12 + 급여외 수당)
SELECT ENAME, SAL, SAL*12+COMM, COMM FROM EMP;

-- 별칭 지정 방식
SELECT ENAME, SAL, SAL*12+COMM AS ANNSAL, COMM FROM EMP;

-- ORDER BY 오름차순
SELECT * FROM EMP ORDER BY SAL;

-- ORDER BY 내림차순
SELECT * FROM EMP ORDER BY SAL DESC;

--각각의 열에 내림차순과 오름차순 동시에 사용하기
SELECT * FROM EMP ORDER BY DEPTNO ASC, SAL DESC;

-- 되새김 문제2
SELECT DISTINCT JOB FROM EMP;

-- 되새김 문제3
SELECT EMPNO AS EMPLOYEE_NO, ENAME AS EMPLOYEE_NAME, MGR AS MANAGER, SAL AS SALARY,
    COMM AS COMMISSION, DEPTNO AS DEPARTMENT_NO
    FROM EMP
ORDER BY DEPARTMENT_NO DESC, EMPLOYEE_NAME ASC; 
