-- unique 지정 테이블 생성
CREATE TABLE table_unique(
    login_id    VARCHAR2(20) UNIQUE,
    login_pwd   VARCHAR2(20) NOT NULL,
    tel         VARCHAR2(20)
    );
    
DESC table_unique;
    
-- 제약 조건 확인
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_UNIQUE'; -- 테이블 이름을 대문자로

-- unique의 성질
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('test_id_01', 'pwd01', '010-1234-5678');

SELECT * FROM TABLE_UNIQUE;

--login_id에 다른 값을 지정
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('test_id_02', 'pwd01', '010-1234-5678');
SELECT * FROM TABLE_UNIQUE;

-- unique와 null
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES(NULL, 'pwd01', '010-1234-5678');
SELECT * FROM TABLE_UNIQUE;

-- UPDATE문으로 NULL부분에 test_id_01을 삽입하면
UPDATE TABLE_UNIQUE SET LOGIN_ID = 'test_id_01' WHERE LOGIN_ID IS NULL;

-- 제약 조건이름을 지정하면서 unique 테이블 생성
create table table_unique2(
    login_id    varchar2(20) constraint tblunq2_lgnid_unique unique,
    login_pwd   varchar2(20) constraint tblunq2_lgnpw_nn not null,
    tel         varchar2(20)
);

-- 데이터 사전 조회
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';

--이미 생성한 테이블에 제약조건 지정
alter table table_unique modify(tel unique);

-- tel 열 모두 null로 변경
UPDATE TABLE_UNIQUE SET TEL=NULL;
SELECT * FROM TABLE_UNIQUE;

-- TABLE_UNIQE TEL에 제약조건 설정
ALTER TABLE TABLE_UNIQUE MODIFY(TEL UNIQUE);
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';

--이미생성한 테이블에 제약 조건 이름 지정
ALTER TABLE TABLE_UNIQUE2 MODIFY(TEL CONSTRAINT TBLUNQ_TEL_UNQ UNIQUE);
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';

--이미 존재하는 UNIQUE제약 조건 이름 수정
ALTER TABLE TABLE_UNIQUE2 RENAME CONSTRAINT TBLUNQ_TEL_UNQ TO TBLUNQ2_TEL_UNQ;
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';

-- UNIQUE 삭제
ALTER TABLE TABLE_UNIQUE2 DROP CONSTRAINT TBLUNQ2_TEL_UNQ;
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';