-- 숫자와 문자열(숫자)를 더하여 출력하기
SELECT EMPNO, EMPNO + '500' FROM EMP
WHERE ENAME = 'SCOTT';

SELECT 'ABCD' + EMPNO, EMPNO FROM EMP
WHERE ENAME = 'SCOTT';

-- 날짜, 숫자 데이터를 문자로 변환하는 TO_CHAR함수
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') AS 현재날짜시간 FROM DUAL;

-- 월과 요일을 다양한 형식으로 출력하기;
SELECT SYSDATE,
       TO_CHAR(SYSDATE, 'MM') AS MM,
       TO_CHAR(SYSDATE, 'MON') AS MON,
       TO_CHAR(SYSDATE, 'MONTH') AS MONTH,
       TO_CHAR(SYSDATE, 'DD') AS DD,
       TO_CHAR(SYSDATE, 'DY') AS DY,
       TO_CHAR(SYSDATE, 'DAY') AS DAY
FROM DUAL;   
-- 특정언어에 맞춰서 날짜 출력
SELECT SYSDATE,
       TO_CHAR(SYSDATE, 'MM') AS MM,
       TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = KOREAN') AS MON_KOR,
       TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = JAPANESE') AS MON_JPN,
       TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = ENGLISH') AS MON_ENG,
       TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = KOREAN') AS MONTH_KOR,
       TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = JAPANESE') AS MONTH_JPN,
       TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = ENGLISH') AS MONTH_ENG
FROM DUAL;

-- TO_NUMBER
SELECT 1300 - '1500',
       '1300' + 1500
      FROM DUAL;
      
SELECT '1,300' - '1,500'
      FROM DUAL;
      
SELECT TO_NUMBER('1,300', '999,999') - TO_NUMBER('1,500', '999,999') FROM DUAL;

-- TO_DATE
SELECT TO_DATE('2024-08-14', 'YYYY-MM-DD') AS TODATE1,
       TO_DATE('2024/08/14', 'YYYY/MM/DD') AS TODATE2
       FROM DUAL;
       
-- 날짜 데이터 간 연산
SELECT * FROM EMP 
WHERE HIREDATE > TO_DATE('1981/06/01', 'YYYY/MM/DD');