-- 1-1 (BEFORE SQL-99)
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
  FROM DEPT D, EMP E
  WHERE D.DEPTNO = E.DEPTNO
  AND E.SAL > 2000
  ORDER BY D.DEPTNO;
  
-- 1-2 (AFTER SQL-99)
SELECT DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
  FROM DEPT D JOIN EMP E USING (DEPTNO)
  WHERE E.SAL > 2000
  ORDER BY DEPTNO;
  
-- 2-1 (BEFORE SQL-99)  
SELECT D.DEPTNO, D.DNAME, 
       TRUNC(AVG(E.SAL)) AS AVG_SAL, MAX(E.SAL) AS MAX_SAL, 
       MIN(E.SAL) AS MIN_SAL, COUNT(*) AS CNT
       FROM DEPT D, EMP E
       WHERE D.DEPTNO = E.DEPTNO
       GROUP BY D.DEPTNO, D.DNAME;

-- 2-2 (AFTER SQL-99)
SELECT D.DEPTNO, D.DNAME, 
       TRUNC(AVG(E.SAL)) AS AVG_SAL, MAX(E.SAL) AS MAX_SAL, 
       MIN(E.SAL) AS MIN_SAL, COUNT(*) AS CNT
       FROM DEPT D JOIN EMP E ON (D.DEPTNO = E.DEPTNO)
       GROUP BY D.DEPTNO, D.DNAME;
       
-- 3-1 (BEFORE SQL-99)    
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
        FROM DEPT D, EMP E
        WHERE D.DEPTNO = E.DEPTNO(+)
        ORDER BY D.DEPTNO, E.ENAME;


-- 3-2 (AFTER SQL-99)
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
        FROM DEPT D LEFT OUTER JOIN EMP E ON(D.DEPTNO = E.DEPTNO)
        ORDER BY D.DEPTNO, E.ENAME;

        
-- 4-1 (BEFORE SQL-99)    
SELECT D.DEPTNO, D.DNAME, 
       E1.EMPNO, E1.ENAME, E1.MGR, E1.SAL, E1.DEPTNO,
       S.LOSAL, S.HISAL, S.GRADE,
       E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME
       FROM DEPT D, EMP E1, EMP E2, SALGRADE S
       WHERE D.DEPTNO = E1.DEPTNO(+)
        AND E1.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
        AND E1.MGR = E2.EMPNO(+)
  ORDER BY D.DEPTNO, E1.EMPNO;
  
-- 4-2 (AFTER SQL-99)
SELECT D.DEPTNO, D.DNAME, 
       E1.EMPNO, E1.ENAME, E1.MGR, E1.SAL, E1.DEPTNO,
       S.LOSAL, S.HISAL, S.GRADE,
       E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME
       FROM DEPT D LEFT OUTER JOIN EMP E1 ON(D.DEPTNO = E1.DEPTNO)
            LEFT OUTER JOIN SALGRADE S ON (E1.SAL BETWEEN S.LOSAL AND S.HISAL)
            LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
  ORDER BY D.DEPTNO, E1.EMPNO;


