-- 급여가 2500 이상인 데이터를 조회
SELECT * FROM EMP WHERE SAL >= 2975;

SELECT SAL FROM EMP WHERE ENAME = 'JONES';

-- 급여가 JONES보다 높은 사원의 데이터를 출력
SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'JONES');

-- 급여가 사원의 평균 급여 이상인 데이터를 조회(서브쿼리)
SELECT  * FROM EMP WHERE SAL >= (SELECT AVG(SAL) FROM EMP);
/* SELECT  * FROM EMP WHERE SAL >= AVG(SAL); 오류 발생
 그룹함수는 무조건 SELECT문 내부에서만 사용해야 한다. */
 
 /*
 SELECT * FROM EMP WHERE SAL >= (SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO);
 오류 발생
 */
 
 SELECT AVG(SAL) FROM EMP;
 
 SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO;
 
-- 단일행 서브쿼리
-- 서브쿼리의 결괏값이 날짜 자료형일 때 SCOTT보다 빨리 입사한 사원
SELECT * FROM EMP
WHERE HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME = 'SCOTT');
SELECT HIREDATE FROM EMP WHERE ENAME = 'SCOTT';

-- 서브 커리 안에서 함수 사용
SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
  WHERE E.DEPTNO = D.DEPTNO
    AND E.DEPTNO = 20
    AND E.SAL > (SELECT AVG(SAL) FROM EMP);

SELECT AVG(SAL) FROM EMP;