-- 다중열 서브쿼리, 서브쿼리의 SELECT절에 비교할 데이터를 여러 개 지정하는 방식
SELECT * FROM EMP
WHERE(DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO);

-- FROM절 서브쿼리(인라인 뷰)
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
  FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10,
       (SELECT * FROM DEPT) D
WHERE E10.DEPTNO = D.DEPTNO; 

-- WITH 절 사용하기
WITH
E10 AS (SELECT * FROM EMP WHERE DEPTNO = 10),
D   AS (SELECT * FROM DEPT)
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
  FROM E10, D
WHERE E10.DEPTNO = D.DEPTNO;

-- SELECT절에 사용하는 서브쿼리(스칼라 서브쿼리)
SELECT EMPNO, ENAME, JOB, SAL,
  (SELECT GRADE FROM SALGRADE WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE,
  DEPTNO,
  (SELECT DNAME FROM DEPT WHERE E.DEPTNO = DEPT.DEPTNO) AS DNAME
  FROM EMP E;
  
  SELECT DEPTNO FROM EMP;
  SELECT * FROM DEPT;