-- 다중행 서브쿼리
-- IN연산자
SELECT * FROM EMP WHERE DEPTNO IN(20, 30);

-- 부서별 최고 급여와 같은 급여를 바는 사원 정보 출력
SELECT * FROM EMP WHERE SAL IN(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO;

--ANY, SOME연산자 서브쿼리 결괏값 중 하나라도 참이면 출력
SELECT * FROM EMP
WHERE SAL = ANY(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

SELECT * FROM EMP
WHERE SAL = SOME(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

/* 30번 부서 사원의 최대 급여보다 적은 급여를 받는 사원 정보 출력
   ANY연산자와 비교연산자 동시 활용 */
SELECT * FROM EMP
  WHERE SAL < ANY(SELECT SAL FROM EMP WHERE DEPTNO = 30)
  ORDER BY SAL, EMPNO;
  
  SELECT SAL FROM EMP WHERE DEPTNO = 30;
  
  

-- ALL 연산자 서브쿼리의 모든 결과가 조건에 참이어야 출력
-- 30번 부서 사원의 최소 급여보다 적은 급여를 받는 사원 정보 출력
SELECT * FROM EMP WHERE SAL < ALL(SELECT SAL FROM EMP WHERE DEPTNO = 30);

SELECT SAL FROM EMP WHERE DEPTNO = 30;

SELECT * FROM EMP WHERE SAL > ALL(SELECT SAL FROM EMP WHERE DEPTNO = 30);

SELECT SAL FROM EMP WHERE DEPTNO = 30;

-- EXISTS 연산자
SELECT * FROM EMP WHERE EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO = 10);

SELECT DNAME FROM DEPT WHERE DEPTNO = 10;

SELECT * FROM EMP WHERE EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO = 50);

SELECT DNAME FROM DEPT WHERE DEPTNO = 50;