--DML 실습
--실습 테이블 만들기
CREATE TABLE DEPT_TEMP AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TEMP;

-- INSERT문
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC) VALUES (50, 'DATABASE', 'SEOUL');
SELECT * FROM DEPT_TEMP;

-- INSERT문 열 지정 생략
INSERT INTO DEPT_TEMP VALUES (60, 'NETWORK', 'BUSAN');
SELECT * FROM DEPT_TEMP;


/* NULL 입력 */
-- 명시적 입력 1
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
  VALUES (70, 'WEB', NULL);
  
-- 명시적 입력 2
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
  VALUES (80, 'MOBILE', '');
SELECT * FROM DEPT_TEMP;

  
-- 암시적 입력
INSERT INTO DEPT_TEMP (DEPTNO, LOC)
  VALUES (90, 'INCHEON');
SELECT * FROM DEPT_TEMP;


/* 날짜 데이터 입력하기 */
CREATE TABLE EMP_TEMP AS SELECT * FROM EMP WHERE 1<>1;
SELECT  * FROM EMP_TEMP;

-- 날짜 데이터 입력(날짜사이 /)
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (9999, '홍길동', 'PERSIDENT', NULL, '2001/01/01', 5000, 1000, 10);

-- 날짜 데이터 입력(날짜사이 -)
INSERT INTO EMP_TEMP
  VALUES (9999, '성춘향', 'MANAGER', 9999, '2001-01-06', 4000, NULL, 20);
  SELECT  * FROM EMP_TEMP;

 -- 일/월/연
 INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (2111, '이순신', 'MANAGER', 9999, '07/01/2001', 4000, NULL, 20);
  
--TO_DATE 사용 날짜 입력
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (2111, '이순신', 'MANAGER', 9999, TO_DATE('07/01/2001', 'DD/MM/YYYY'), 4000, NULL, 20);
SELECT  * FROM EMP_TEMP;

-- SYSDATE 사용 날짜 입력
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);
SELECT  * FROM EMP_TEMP;

-- 서브쿼리 사용하여 한번에 여러 데이터 추가
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
      SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
        FROM EMP E, SALGRADE S
      WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
        AND S.GRADE = 1;
  SELECT  * FROM EMP_TEMP;