--DEPT 복사 DEPT_TEMP2만들기
CREATE TABLE DEPT_TEMP2 
  AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;

-- UPDATE
UPDATE DEPT_TEMP2 SET LOC = 'SEOUL';
SELECT * FROM DEPT_TEMP2;

-- ROLLBACK
ROLLBACK;
SELECT * FROM DEPT_TEMP2;

-- 데이터 일부만 수정
UPDATE DEPT_TEMP2 SET DNAME = 'DATABASE', LOC = 'SEOUL'
  WHERE DEPTNO = 40;
SELECT * FROM DEPT_TEMP2;


-- 서브쿼리를 사용하여 데이터 수정
-- 여러 열 한번에 수정
UPDATE DEPT_TEMP2
  SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = 40)
  WHERE DEPTNO = 40;
SELECT * FROM DEPT_TEMP2;
  
-- 열 하나하나 수정하기
UPDATE DEPT_TEMP2
  SET DNAME = (SELECT DNAME FROM DEPT WHERE DEPTNO = 40),
      LOC = (SELECT LOC FROM DEPT WHERE DEPTNO = 40)
 WHERE DEPTNO = 40;     
 
-- WHERE 절에 서브쿼리 활용하여 데이터 수정
UPDATE DEPT_TEMP2 SET LOC = 'SEOUL'
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT_TEMP2 WHERE DNAME = 'OPERATIONS');

