-- 집합연산자를 활용하여 부서별 평균급여 산츨
SELECT AVG(SAL), '10' AS DEPTNO FROM EMP WHERE DEPTNO = 10
  UNION ALL
SELECT AVG(SAL), '20' AS DEPTNO FROM EMP WHERE DEPTNO = 20
  UNION ALL
SELECT AVG(SAL), '30' AS DEPTNO FROM EMP WHERE DEPTNO = 30;

-- GROUP BY
SELECT AVG(SAL), DEPTNO FROM EMP
GROUP BY DEPTNO;

-- GROUP BY ORDER BY
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

-- GROUP BY절을 사용할 때 일반 열은 GROUP BY에 지정하지 않으면 SELECT절에서 사용X
SELECT ENAME, DEPTNO, AVG(SAL) FROM EMP 
GROUP BY DEPTNO;

-- HAVING절
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP
  GROUP BY DEPTNO, JOB
  HAVING AVG(SAL) >= 2000 -- 그룹화한 대상의 출력을 제한
  ORDER BY DEPTNO, JOB;
  
  SELECT DEPTNO, JOB, AVG(SAL) FROM EMP
  GROUP BY DEPTNO, JOB
  ORDER BY DEPTNO, JOB;
  
-- HAVING절과 WHERE절
SELECT DEPTNO, JB, AVG(SAL) FROM EMP
  WHERE AVG(SAL) >= 2000 -- WHERE는 출력 행을 제한
  GROUP BY DEPTNO, JOB
  ORDER BY DEMPTNO, JOB;
  
-- WHERE절 HAVING절 모두 사용, WHERE절을 먼저 실행하고 HAVING절 실행
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP
  WHERE SAL <= 3000
  GROUP BY DEPTNO, JOB
  HAVING AVG(SAL) >= 2000 -- 그룹화한 대상의 출력을 제한
  ORDER BY DEPTNO, JOB;
