SELECT SUM(SAL) FROM EMP;

SELECT JOB, SUM(SAL) FROM EMP
GROUP BY JOB;

SELECT SUM(COMM) FROM EMP;

--SUM 함수와 DISTNCT, ALL 함꼐 사용
SELECT SUM(DISTINCT SAL),
       SUM(ALL SAL),
       SUM(SAL)
FROM EMP;

--데이터 개수를 구하는 함수(COUNT)
SELECT COUNT(*) FROM EMP;
-- 부서 번호가 30번인 직원 수 구하기
SELECT COUNT(*) FROM EMP WHERE DEPTNO = 30;

-- COUNT함수와 DISTINCT, ALL 동시에 사용
SELECT COUNT(DISTINCT SAL),
       COUNT(ALL SAL),
       COUNT(ALL SAL)
FROM EMP;

-- COUNT에서 NULL은 데이터 반환 개수에서 제외한다.
SELECT COUNT(COMM) FROM EMP;
SELECT COUNT(COMM) FROM EMP WHERE COMM IS NOT NULL;

-- MAX MIN
SELECT MAX(SAL) FROM EMP
WHERE DEPTNO = 10;

SELECT MIN(SAL) FROM EMP
WHERE DEPTNO = 10;

-- 날짜 데이터 MIN MAX
SELECT MAX(HIREDATE) FROM EMP
WHERE DEPTNO = 20;

SELECT MIN(HIREDATE) FROM EMP
WHERE DEPTNO = 20;

-- AVG
SELECT AVG(SAL) FROM EMP
WHERE DEPTNO = 30;

--DISTINCT 활용
SELECT AVG(DISTINCT SAL) FROM EMP
WHERE DEPTNO = 30;







