-- 뷰 생성
CREATE VIEW VW_EMP20
  AS(SELECT EMPNO, ENAME, JOB, DEPTNO
     FROM EMP
     WHERE DEPTNO = 20);
     
-- USER_VIEWS 데이터 사전 확인
SELECT * FROM USER_VIEWS;

-- 생성한 뷰 조회
SELECT * FROM VW_EMP20;

-- 뷰 삭제
DROP VIEW VW_EMP20;

-- USER_VIEWS 데이터 사전 확인
SELECT * FROM USER_VIEWS;

/* 인라인 뷰 */
-- ROWNUM 추가로 조회 ROWNUM: 의사열이라고 하는 특수 열
SELECT ROWNUM, E.*
FROM EMP E;

-- EMP 테이블을 SAL열 기준으로 정렬
SELECT ROWNUM, E.*
  FROM EMP E
  ORDER BY SAL DESC;
  
-- ROWNUM 인라인 뷰에 적용
-- 인라인뷰(서브쿼리)
SELECT ROWNUM, E.*
  FROM (SELECT * FROM EMP E
        ORDER BY SAL DESC) E;
        
-- 인라인 뷰(WITH절)
WITH E AS (SELECT * FROM EMP E ORDER BY SAL DESC)
SELECT ROWNUM, E.* FROM E;

-- TOP-N 추출(서브쿼리)
SELECT ROWNUM, E.* FROM (SELECT * FROM EMP E ORDER BY SAL DESC) E
  WHERE ROWNUM <= 3;

-- TOP-N 추출 (WITH절)
WITH E AS (SELECT * FROM EMP E ORDER BY SAL DESC)
SELECT ROWNUM, E.* FROM E WHERE ROWNUM <= 3;