CREATE TABLE DEPT_TCL AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TCL;

-- 데이터 입력
INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;

DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

SELECT * FROM DEPT_TCL;

-- ROLLBACK으로 명령어 실행 취소
ROLLBACK;
SELECT * FROM DEPT_TCL;

-- 트랜잭션을 영구히 반영 COMMIT
INSERT INTO DEPT_TCL VALUES(50, 'NETWORK', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 20;

DELETE FROM DEPT_TCL WHERE DEPTNO = 40;

SELECT * FROM DEPT_TCL;

COMMIT;
SELECT * FROM DEPT_TCL;

-- COMMIT한 트랜잭션은 ROLLBACK불가
ROLLBACK;
SELECT * FROM DEPT_TCL;

